### ISSUE TITLE
Non-public listings to support development and testing of a portal: is that an accepted practice?

### ISSUE THREAD

**Issue by lestephane** [awsdocs/aws-marketplace-user-guide-for-sellers#8]
Here is my use case:
- We have a product listing (let's call it 'Our Product') which is public
- The confirmation URL for the product points to the live version of our portal (say v1)
- I'm now working on portal v2, and I need to be able to try and test my changes in a tight feedback loop. Ideally v2 is running on my local machine during development

Is it possible / advisable / recommended to create a 'clone' of the product listing for each environment that will need to run tests? 

We'd have 
- A public `Our Product` listing with confirmation URL `https://production.ourcompany.com/api/marketplace-confirm/<usagePlanId>` (the production portal)
- A non-public `Our Product (localhost:3000)` listing with confirmation URL `http:/localhost:3000/api/marketplace-confirm/<usagePlanId>` (to develop locally)
- A non-public `Our Product (CI)` listing with confirmation URL `https://ci.ourcompany.com/api/marketplace-confirm/<usagePlanId>` (to run our continuous integration)

Assuming it is OK to use one listing for each environment as shown above, is it sufficient to take the existing listing, change the name and confirmation URL, and submit that as new listing? Or do I have to consider other aspects? Will it take long for AWS to review the listing? If so, how do I signal that this is strictly development and testing related, and will never be made public?

The user guide is pretty vague on developability aspects of developing a SaaS portal. I'm hoping to kick the discussion into gear with this issue.

**Comment by lestephane** [comment]
I've just realized that since the POST request to the confirmation URL is issued by Amazon, there is no way to receive the request on a locally running server (in other words http://localhost won't work). Still, this is a requirement for developability. So if you know a way to make a public URL that forwards all traffic to a localhost endpoint, I'm interested. This issue remains relevant in my view.

**Comment by lestephane** [comment]
I've tried https://serveo.net successfully to make a local development server available at a predictable & repeatable public URL. So that can be done.

**Comment by dylanrush** [comment]
The only reason localhost may not work because you may not be able to publish a limited-visibility test product using a URL that AWS Marketplace cannot reach. That prevents sellers from inadvertently publishing products with unreachable URLs.

There is a way to test registration URLs without publishing a new product. You can intercept the registration token in your browser's development console (pressing F12 in Chrome) while clicking the blue signup link. Then, you can use this form to POST your registration token to any URL.

https://s3.amazonaws.com/awsmp-saas-beta-sdk/SaaSBillingRegistrationTester.html

Here is a screenshot showing where you can find the registration token in your developer console: https://i.imgur.com/43x2ai6.png

**Comment by lestephane** [comment]
I'm coming from a CI angle. So I need a solution that works without a human being sitting there in front of the browser in the dev console. How would I intercept the registration token with Selenium for example?
